pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo hi'
            }
        }
        stage('Test') {
            steps {
                sh 'echo testing'
            }
            post {
                always {
                    sh 'echo results'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo sending'
            }
        }
    }
    post {
        success {
            slackSend(channel: '#jenkins-cli', message: "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)", teamDomain: 'project1-raw6296', tokenCredentialId: 'slack-notify')
        }
        failure {
            slackSend(channel: '#jenkins-cli', message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)", teamDomain: 'project1-raw6296', tokenCredentialId: 'slack-notify')
        }
    }
}
